---
title: "country_data"
author: "Andre Ferreira"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinythemes)
library(PPBDS.data)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(gganimate)
library(plotly)
library(sf)
library(rgdal)
library(rnaturalearth)
library(rnaturalearthdata)
library(gtsummary)
library(magick)

```

```{r}

country_data <- read_csv("owid-co2-data.csv",
                         col_types = cols(
                           .default = col_double(),
                           iso_code = col_character(),
                           country = col_character()
                         )) %>%
  drop_na(iso_code) %>%
  filter(year >= 1990,
         country != "World")

write_rds(country_data, "country_data.rds")

```

```{r}

        world <- ne_countries(scale = "medium", returnclass = "sf") %>%
            rename("country" = name,
                   "iso_code" = sov_a3) 

write_rds(world, "world.rds")
        
        country_data_2 <- country_data %>%
            select(country, year, share_global_co2, iso_code) %>%
            filter(year == 2018,
                   iso_code != "OWID_WRL") 
        
write_rds(country_data_2, "country_data_2.rds")
        
        world_map <- full_join(world, country_data_2, by = "country") 
        
        world_map <- world_map %>%
          ggplot() +
            geom_sf(aes(fill = share_global_co2)) +
            labs(title = "World Plot Depicting Global CO2 Share") +
            scale_fill_continuous(name = "Percentage of CO2 Share")
        
        ggsave("world_map.png", world_map, height = 2, width = 2) 
        
write_rds(world_map, "world_map.rds")

```


